[teensy_base]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
build_flags = -Wall
lib_deps = 
    Adafruit NeoPixel
    adafruit/Adafruit BNO08x@^1.2.4
    dfrobot/DFRobot_URM09@^1.2.0
    adafruit/Adafruit SSD1306@^2.5.17
    adafruit/Adafruit GFX Library@^1.12.6


; 2. YOUR EXISTING TEENSY ENVS (Now inheriting from teensy_base)
[env:ir_sensor]
extends = teensy_base
build_flags = 
    ${teensy_base.build_flags}
    -DIR_SENSOR_BOARD
build_src_filter = 
    +<ir_sensor/> -<line_sensor/> -<main_defender/> -<main_attacker/> -<distance_sensor/>

[env:line_sensor]
extends = teensy_base
build_flags = 
    ${teensy_base.build_flags}
    -DLINE_SENSOR_BOARD
build_src_filter = 
    +<line_sensor/> -<ir_sensor/> -<main_defender/> -<main_attacker/> -<distance_sensor/>

[env:main_defender]
extends = teensy_base
build_flags = 
    ${teensy_base.build_flags}
    -DGOALKEEPER
build_src_filter = 
    +<main_defender/> -<ir_sensor/> -<line_sensor/> -<main_attacker/> -<distance_sensor/>

[env:main_attacker]
extends = teensy_base
build_flags = 
    ${teensy_base.build_flags}
    -DATTACKER
build_src_filter = 
    +<main_attacker/> -<ir_sensor/> -<line_sensor/> -<main_defender/> -<distance_sensor/>


; ESP32-C6 CONFIGURATION
[env:distance_sensor]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-esp32-c6
framework = arduino
monitor_speed = 115200
build_flags = -Wall -DESP32
; lib_deps = 
;    lib/distance-sensor  
build_src_filter = 
    +<distance_sensor/>
    -<ir_sensor/>
    -<line_sensor/>
    -<main_defender/>
    -<main_attacker/>